### ISSUE TITLE
Shortform functions not working in YAML templates

### ISSUE THREAD

**Issue by geerlingguy** [acquia/moonshot#223]
I've converted my moonshot templates from JSON to YAML using [aws-cfn-template-flip](https://github.com/awslabs/aws-cfn-template-flip), and when I'm creating new infrastructure using `moonshot create`, I get errors like:

```
--> CREATE_FAILED QueueSecurityGroup The vpc ID 'VpcId' does not exist
```

This seems to occur because I'm using the [short form of the `Ref` function](http://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/intrinsic-function-reference-ref.html), like so:

```yaml
VpcId: !Ref VpcId
```

If I convert all my templates to use the more verbose/annoying full function form, like:

```yaml
VpcId:
  Ref: VpcId
```

Then it seems to work.

Is moonshot reformatting the YAML before sending it across the CloudFormation? The templates in CloudFormation's UI seem to show that any of the short form functions are stripped out (e.g. it shows `VpcId: VpcId`, which is obviously going to fail...).

**Comment by geerlingguy** [comment]
Same thing with any of the different Intrinsic Functions, for example:

These work:

```yaml
ImageId:
  Fn::FindInMap: [Region2AMI, Ref: 'AWS::Region', AMI]
...
SubnetId:
  Fn::Select: ['0', Ref: 'Subnets']
```

But the short syntax versions don't:

```yaml
ImageId: !FindInMap [Region2AMI, !Ref 'AWS::Region', AMI]
...
SubnetId: !Select ['0', !Ref 'Subnets']
```

**Comment by geerlingguy** [comment]
And as an aside, after finishing the conversion from JSON to YAML... _WOW_ it's so much easier to work with these templates.

**Comment by tallandroid** [comment]
Did you get a solution for this one ?

**Comment by geerlingguy** [comment]
@tallandroid - We switched to running the CloudFormation templates with Ansible.

**Comment by jimohalloran** [comment]
Wanted to add that I've also run into this same issue.  It's as though Moonshot when it parses/validates the YAML is stripping out the ! function calls before the template is passed to CloudFormation itself.

So for example:

```YAML
Outputs:
  DrawingName:
    Value: !Sub
      - '${stack}-be-drawings'
      - { stack: !Ref 'AWS::StackName'}
```

... fails because the !Sub is stripped out and the Value of an output can't be a List.

This also doesn't work as expected:
```YAML
Outputs:
  DrawingName:
    Value: !Sub '${AWS::StackName}-be-drawings'
```
This passes validation, but when you run it via Moonshot the output is set to the literal string '${AWS::StackName}-be-drawings', which is clearly not what was intended.

The same occurs with !Join, so presumably this is all CloudFormation functions when written with the ! shorthand syntax.

If I execute a stack update in the AWS console directly with either of the code samples above, it works as expected, so it seems as though it's Moonshot interfering with the YAML.

I'm running Moonshot 2.0.0beta5 on Ruby 2.5.3p105.  I'm happy to provide any other details about my environment that might be required to repro this.  In fact, I could supply a complete docker container if needed.
