### ISSUE TITLE
Short hand yaml Ref fails to detect the resource when created

### ISSUE THREAD

**Issue by kamirendawkins** [acquia/moonshot#242]
Fails to detect that the VPC exists even though it is created.
```VPCGatewayAttachment:
    Type: AWS::EC2::VPCGatewayAttachment
    Properties:
      VpcId: !Ref VPC
      InternetGatewayId:
        Ref: InternetGateway
```

Functional in long hand form:
```
VPCGatewayAttachment:
    Type: AWS::EC2::VPCGatewayAttachment
    Properties:
      VpcId:
        Ref: VPC
      InternetGatewayId:
        Ref: InternetGateway
```

https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/intrinsic-function-reference-ref.html
